MAIN_WINDOW_START_POSITION_X = 100
MAIN_WINDOW_START_POSITION_Y = 100

MAIN_WINDOW_SIZE_X = 500
MAIN_WINDOW_SIZE_Y = 500

RECT_SIZE_X = 100
RECT_SIZE_Y = 50


ADD_RECT_BUTTON = "New rect"
ADD_LINK_BUTTON = "New link"

MOVE_RECT_BUTTON = "Move rect"

CLEAR_DRAW_AREA_BUTTON = "Clear"