from PyQt5.QtCore import Qt

MAIN_WINDOW_START_POSITION_X = 100
MAIN_WINDOW_START_POSITION_Y = 100

MAIN_WINDOW_SIZE_X = 500
MAIN_WINDOW_SIZE_Y = 500

RECT_SIZE_X = 100
RECT_SIZE_Y = 50
RECT_DEFAULT_COLOR = Qt.GlobalColor.black

ADD_RECT_BUTTON = "New rect"
ADD_LINK_BUTTON = "New link"

MOVE_SHAPE_BUTTON = "Move shape"

CLEAR_DRAW_AREA_BUTTON = "Clear"